name: Build Mod Pack
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUM: ${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install python deps
        run: pip install -r .github/workflows/scripts/requirements.txt

      - name: Build pack
        id: build
        run: python .github/workflows/scripts/build.py >> "$GITHUB_OUTPUT"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ steps.build.outputs.name }}
          path: build/**
