name: Build Mod Pack
on: push

jobs:
  generate:
    name: Generate FTB Quest Translate Keys
    secrets: inherit
    permissions:
      contents: write
    uses: ./.github/workflows/ftbquest.yml

  crowdin:
    needs:
      - generate
    name: Update Crowdin Sources / Translations
    secrets: inherit
    permissions:
      contents: write
    uses: ./.github/workflows/crowdin.yml

  build:
    name: Build Modpack
    needs:
      - crowdin
    runs-on: ubuntu-latest
    env:
      BUILD_NUM: ${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install python deps
        run: pip install -r .github/workflows/scripts/requirements.txt

      - name: Build pack
        id: build
        run: python .github/workflows/scripts/build.py >> "$GITHUB_OUTPUT"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ steps.build.outputs.name }}
          path: build/**
